version: "3.9"
services:
  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - "8000:8000" 

  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "6000:80" 
