name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Build and push Docker images
      - name: Build and push Docker images
        run: |
          docker build -t your-dockerhub-username/feedback-client:latest ./client
          docker build -t your-dockerhub-username/feedback-server:latest ./server
          docker push your-dockerhub-username/feedback-client:latest
          docker push your-dockerhub-username/feedback-server:latest

      # SSH into EC2 and deploy
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/feedback-client:latest
            docker pull your-dockerhub-username/feedback-server:latest
            docker stop feedback-client || true
            docker stop feedback-server || true
            docker rm feedback-client || true
            docker rm feedback-server || true
            docker run -d --name feedback-client -p 80:80 your-dockerhub-username/feedback-client:latest
            docker run -d --name feedback-server -p 8000:8000 your-dockerhub-username/feedback-server:latest
